import { Hackathon, Team, TeamRequest, Message, Notification, Teammate } from "@/types";

export const FEATURED_HACKATHONS: Hackathon[] = [
  {
    id: "h1",
    title: "AI Innovation Challenge",
    organizer: "TechCorp India",
    description: "Build AI solutions for real-world problems. Open to all developers worldwide.",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=200&fit=crop",
    mode: "Online",
    prize: "₹1,00,000",
    prizeAmount: 100000,
    tags: ["AI", "ML", "Data Science"],
    daysLeft: 2,
    participants: 325,
    startDate: "2026-06-20",
    endDate: "2026-06-22",
    registrationDeadline: "2026-06-15",
    featured: true,
    difficulty: "Intermediate",
    teamSize: "2-4",
    status: "open",
  },
  {
    id: "h2",
    title: "Smart India Hackathon 2025",
    organizer: "Government of India",
    description: "National level innovation competition by Govt. of India. Solve real national challenges.",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=400&h=200&fit=crop",
    mode: "Offline",
    prize: "₹2,00,000",
    prizeAmount: 200000,
    tags: ["IoT", "Problem Solving", "Web"],
    daysLeft: 5,
    participants: 800,
    startDate: "2026-07-01",
    endDate: "2026-07-03",
    registrationDeadline: "2026-06-18",
    featured: false,
    difficulty: "Advanced",
    teamSize: "4-6",
    status: "open",
  },
  {
    id: "h3",
    title: "Sustain & Solve",
    organizer: "GreenTech Foundation",
    description: "Tech for sustainability and climate action. Build solutions that matter for the planet.",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=200&fit=crop",
    mode: "Online",
    prize: "₹75,000",
    prizeAmount: 75000,
    tags: ["Green Tech", "IoT", "AI"],
    daysLeft: 6,
    participants: 210,
    startDate: "2026-06-25",
    endDate: "2026-06-27",
    registrationDeadline: "2026-06-20",
    featured: false,
    difficulty: "Beginner",
    teamSize: "2-3",
    status: "open",
  },
  {
    id: "h4",
    title: "Hack The Future 3.0",
    organizer: "FutureBuilders",
    description: "Build the next generation of web solutions. Frontend-focused mega hackathon.",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=200&fit=crop",
    mode: "Online",
    prize: "₹1,50,000",
    prizeAmount: 150000,
    tags: ["Web", "Blockchain", "AI"],
    daysLeft: 7,
    participants: 320,
    startDate: "2026-06-28",
    endDate: "2026-06-30",
    registrationDeadline: "2026-06-22",
    featured: false,
    difficulty: "Intermediate",
    teamSize: "3-5",
    status: "open",
  },
  {
    id: "h5",
    title: "HealthTech Innovation 2026",
    organizer: "MedTech Alliance",
    description: "Revolutionize healthcare with technology. AI, IoT, and mobile health solutions.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=200&fit=crop",
    mode: "Hybrid",
    prize: "₹3,00,000",
    prizeAmount: 300000,
    tags: ["HealthTech", "AI", "Mobile"],
    daysLeft: 12,
    participants: 450,
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    registrationDeadline: "2026-07-01",
    featured: false,
    difficulty: "Advanced",
    teamSize: "3-5",
    status: "open",
  },
  {
    id: "h6",
    title: "FinHack 2026",
    organizer: "PayTech India",
    description: "Build innovative fintech solutions. Payments, lending, insurance and more.",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=200&fit=crop",
    mode: "Online",
    prize: "₹5,00,000",
    prizeAmount: 500000,
    tags: ["FinTech", "Blockchain", "AI"],
    daysLeft: 15,
    participants: 600,
    startDate: "2026-07-15",
    endDate: "2026-07-17",
    registrationDeadline: "2026-07-05",
    featured: true,
    difficulty: "Advanced",
    teamSize: "2-4",
    status: "open",
  },
];

export const LIVE_TEAM_REQUESTS: TeamRequest[] = [
  {
    id: "tr1",
    teamName: "Mission Possible",
    requiredRole: "ML Engineer",
    members: 3,
    maxMembers: 4,
    location: "Online",
    matchScore: 95,
    isOnline: true,
    teamLeader: "Rahul K",
    hackathon: "AI Innovation Challenge",
    color: "#7C5CFF",
    icon: "🎯",
    extraMembers: 2,
  },
  {
    id: "tr2",
    teamName: "CodeCrafters",
    requiredRole: "Backend Developer",
    members: 2,
    maxMembers: 4,
    location: "Bangalore",
    matchScore: 92,
    isOnline: true,
    teamLeader: "Priya S",
    hackathon: "Hack The Future 3.0",
    color: "#4F7CFF",
    icon: "💻",
    extraMembers: 1,
  },
  {
    id: "tr3",
    teamName: "Design Dynasty",
    requiredRole: "UI/UX Designer",
    members: 3,
    maxMembers: 5,
    location: "Mumbai",
    matchScore: 90,
    isOnline: false,
    teamLeader: "Ananya M",
    hackathon: "Smart India Hackathon",
    color: "#22C55E",
    icon: "🎨",
    extraMembers: 2,
  },
  {
    id: "tr4",
    teamName: "AI Warriors",
    requiredRole: "Frontend Developer",
    members: 2,
    maxMembers: 4,
    location: "Chennai",
    matchScore: 88,
    isOnline: false,
    teamLeader: "Karthik R",
    hackathon: "Sustain & Solve",
    color: "#F59E0B",
    icon: "⚔️",
    extraMembers: 1,
  },
];

export const TEAMMATES: Teammate[] = [
  {
    id: "tm1",
    name: "Devansh Verma",
    role: "Backend Developer",
    location: "Mumbai, India, India",
    skills: ["Node.js", "Express", "MongoDB"],
    rating: 4.8,
    matchScore: 95,
    isOnline: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=devansh&backgroundColor=c0aede",
    college: "IIT Bombay",
  },
  {
    id: "tm2",
    name: "Ananya Singh",
    role: "ML Engineer",
    location: "Bangalore, India",
    skills: ["Python", "TensorFlow", "PyTorch"],
    rating: 4.9,
    matchScore: 93,
    isOnline: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ananya&backgroundColor=ffd5dc",
    college: "BITS Pilani",
  },
  {
    id: "tm3",
    name: "Rohit Kumar",
    role: "Frontend Developer",
    location: "Delhi, India",
    skills: ["React", "Next.js", "Tailwind"],
    rating: 4.7,
    matchScore: 92,
    isOnline: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rohit&backgroundColor=b6e3f4",
    college: "Delhi University",
  },
  {
    id: "tm4",
    name: "Ishita Das",
    role: "UI/UX Designer",
    location: "Kolkata, India",
    skills: ["Figma", "Adobe XD", "UI Design"],
    rating: 4.6,
    matchScore: 90,
    isOnline: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ishita&backgroundColor=d1f7c4",
    college: "NIT Durgapur",
  },
  {
    id: "tm5",
    name: "Arjun Nair",
    role: "Full Stack Developer",
    location: "Pune, India",
    skills: ["React", "Node.js", "PostgreSQL"],
    rating: 4.8,
    matchScore: 89,
    isOnline: false,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=arjun&backgroundColor=ffdfbf",
    college: "COEP",
  },
];

export const MY_TEAMS: Team[] = [
  {
    id: "team1",
    name: "AI Resume Screener",
    hackathon: "AI Innovation Challenge",
    members: [
      { id: "1", name: "Alex S", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex", role: "Full Stack" },
      { id: "2", name: "Priya K", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya", role: "ML" },
      { id: "3", name: "Rahul M", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahul", role: "Frontend" },
    ],
    maxMembers: 4,
    progress: 78,
    status: "active",
    requiredRoles: ["Data Scientist"],
    description: "AI-powered resume screening and matching system",
    category: "AI/ML",
    color: "#7C5CFF",
    icon: "🤖",
  },
  {
    id: "team2",
    name: "GreenConnect",
    hackathon: "Sustain & Solve",
    members: [
      { id: "1", name: "Alex S", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex", role: "Full Stack" },
      { id: "2", name: "Meera R", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=meera", role: "Designer" },
    ],
    maxMembers: 3,
    progress: 60,
    status: "recruiting",
    requiredRoles: ["Backend Developer"],
    description: "Connecting sustainable businesses with consumers",
    category: "Sustainability",
    color: "#22C55E",
    icon: "🌱",
  },
  {
    id: "team3",
    name: "PrepHub",
    hackathon: "FinHack 2026",
    members: [
      { id: "1", name: "Alex S", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex", role: "Full Stack" },
      { id: "2", name: "Kiran T", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kiran", role: "Backend" },
      { id: "3", name: "Sana A", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sana", role: "UI/UX" },
    ],
    maxMembers: 4,
    progress: 40,
    status: "recruiting",
    requiredRoles: ["ML Engineer"],
    description: "EdTech platform for placement preparation",
    category: "EdTech",
    color: "#4F7CFF",
    icon: "📚",
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "team",
    title: "Team invitation received",
    description: "Mission Possible invited you to join as ML Engineer",
    timestamp: "2 minutes ago",
    read: false,
    actionUrl: "/my-requests",
    actionLabel: "View Invite",
  },
  {
    id: "n2",
    type: "hackathon",
    title: "Registration closing soon",
    description: "AI Innovation Challenge registration closes in 2 days",
    timestamp: "1 hour ago",
    read: false,
    actionUrl: "/discover",
    actionLabel: "Register Now",
  },
  {
    id: "n3",
    type: "team",
    title: "Join request accepted",
    description: "CodeCrafters accepted your request to join",
    timestamp: "3 hours ago",
    read: true,
    actionUrl: "/my-teams",
    actionLabel: "View Team",
  },
  {
    id: "n4",
    type: "profile",
    title: "Trust Score increased",
    description: "Your trust score increased to 85% after connecting GitHub",
    timestamp: "1 day ago",
    read: true,
  },
  {
    id: "n5",
    type: "hackathon",
    title: "New hackathon recommended",
    description: "HealthTech Innovation 2026 matches your skills",
    timestamp: "2 days ago",
    read: true,
    actionUrl: "/discover",
    actionLabel: "Learn More",
  },
];

export const MESSAGES: Message[] = [
  {
    id: "m1",
    senderId: "u2",
    senderName: "Rahul Kumar",
    content: "Hey! Are you available for the hackathon next week?",
    timestamp: "10:30 AM",
    read: false,
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahul",
  },
  {
    id: "m2",
    senderId: "team1",
    senderName: "AI Resume Screener",
    content: "Priya: Just pushed the ML model update 🚀",
    timestamp: "9:45 AM",
    read: false,
    teamChat: true,
    teamName: "AI Resume Screener",
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
  },
  {
    id: "m3",
    senderId: "u3",
    senderName: "Ananya Singh",
    content: "Check out this cool AI paper I found!",
    timestamp: "Yesterday",
    read: true,
    senderAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ananya",
  },
];
